### ISSUE TITLE
Check required packages

### ISSUE THREAD

**Issue by stakats** [DHARPA-Project/kiara_plugin.dh_tagung_2023#3]
In the NA notebook's opening cell we have:

```
import csv
import networkx as nx
import matplotlib.pyplot as plt
```

Are these actually required? Commenting them out seems to have no effect on the notebook.

**Comment by yaslena** [comment]
I think we are not using csv in this notebook, but we are using networkx in this line (25):

```
network = nx.read_graphml('CKCC_kiara_network.graphml')
nx.draw(network)
```

And matplotlib is a requirement for nx.draw although the plt variable is not used.

**Comment by yaslena** [comment]
Apparently, the visualisation with networkX draw was a later addition to the notebook. We are keeping it for now, and therefore also keeping networkx and matplotlib.

Removing import csv from the notebook and closing this issue.
