### ISSUE TITLE
Install playground dependency in NA notebook

### ISSUE THREAD

**Issue by stakats** [DHARPA-Project/kiara_plugin.dh_tagung_2023#5]
We should check for and install playground so that it doesn't have to be done externally

**Comment by makkus** [comment]
If there is any required code that currently lives in the playground, we should move it to a 'tagung'-specific repo/package, otherwise stuff will break certainly in the future.

**Comment by yaslena** [comment]
All additionally required modules have been moved to the 'tagung' repo, so the notebook now runs through without having to install playground.
Closing this issue.
